/* Autogenerated file. Do not edit manually. */

/* eslint-disable max-classes-per-file */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable @typescript-eslint/consistent-type-imports */

/*
  Fuels version: 0.98.0
*/

export {ArcanaVault} from './ArcanaVault';
export {ArcanaVaultFactory} from './ArcanaVaultFactory';
