'use strict'
/* Autogenerated file. Do not edit manually. */
Object.defineProperty(exports, '__esModule', { value: true })
exports.ArcanaVaultFactory = exports.ArcanaVault = void 0

/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable @typescript-eslint/consistent-type-imports */
/*
  Fuels version: 0.98.0
*/
const ArcanaVault_1 = require('./ArcanaVault')
Object.defineProperty(exports, 'ArcanaVault', { enumerable: true, get: function () { return ArcanaVault_1.ArcanaVault } })
const ArcanaVaultFactory_1 = require('./ArcanaVaultFactory')
Object.defineProperty(exports, 'ArcanaVaultFactory', { enumerable: true, get: function () { return ArcanaVaultFactory_1.ArcanaVaultFactory } })
