// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.5
//   protoc               v6.33.1
// source: cosmos.proto

/* eslint-disable */
import { grpc } from "@improbable-eng/grpc-web";
import { BrowserHeaders } from "browser-headers";
import Long from "long";
import {
  QueryAllPendingClaimsRequest,
  QueryAllPendingClaimsResponse,
  QueryAllPendingSettlementsRequest,
  QueryAllPendingSettlementsResponse,
  QueryAllRequestForFundsRequest,
  QueryAllRequestForFundsResponse,
  QueryAllSettlementRequest,
  QueryAllSettlementResponse,
  QueryAllSolverDataRequest,
  QueryAllSolverDataResponse,
  QueryGetPendingClaimsRequest,
  QueryGetPendingClaimsResponse,
  QueryGetPendingSettlementsRequest,
  QueryGetPendingSettlementsResponse,
  QueryGetProtocolFeesRequest,
  QueryGetProtocolFeesResponse,
  QueryGetRequestForFundsRequest,
  QueryGetRequestForFundsResponse,
  QueryGetSettlementRequest,
  QueryGetSettlementResponse,
  QueryGetSolverDataRequest,
  QueryGetSolverDataResponse,
} from "./definition";

export const protobufPackage = "xarchain.chainabstraction.v1";

// If `window` is undefined it means that we running in backend mode thus we need to use NodeHttpTransport
if (typeof window === undefined) {
  (async function () {
    const lib = await import('@improbable-eng/grpc-web-node-http-transport');
    grpc.setDefaultTransport(lib.NodeHttpTransport())
  })()
}

export interface Query {
  /** ListRequestForFunds Queries a list of RequestForFunds items. */
  GetRequestForFunds(
    request: DeepPartial<QueryGetRequestForFundsRequest>,
    metadata?: grpc.Metadata,
  ): Promise<QueryGetRequestForFundsResponse>;
  /** ListRequestForFunds defines the ListRequestForFunds RPC. */
  ListRequestForFunds(
    request: DeepPartial<QueryAllRequestForFundsRequest>,
    metadata?: grpc.Metadata,
  ): Promise<QueryAllRequestForFundsResponse>;
  /** ListPendingClaims Queries a list of PendingClaims items. */
  GetPendingClaims(
    request: DeepPartial<QueryGetPendingClaimsRequest>,
    metadata?: grpc.Metadata,
  ): Promise<QueryGetPendingClaimsResponse>;
  /** ListPendingClaims defines the ListPendingClaims RPC. */
  ListPendingClaims(
    request: DeepPartial<QueryAllPendingClaimsRequest>,
    metadata?: grpc.Metadata,
  ): Promise<QueryAllPendingClaimsResponse>;
  /** ListPendingSettlements Queries a list of PendingSettlements items. */
  GetPendingSettlements(
    request: DeepPartial<QueryGetPendingSettlementsRequest>,
    metadata?: grpc.Metadata,
  ): Promise<QueryGetPendingSettlementsResponse>;
  /** ListPendingSettlements defines the ListPendingSettlements RPC. */
  ListPendingSettlements(
    request: DeepPartial<QueryAllPendingSettlementsRequest>,
    metadata?: grpc.Metadata,
  ): Promise<QueryAllPendingSettlementsResponse>;
  /** Queries a ProtocolFees by index. */
  GetProtocolFees(
    request: DeepPartial<QueryGetProtocolFeesRequest>,
    metadata?: grpc.Metadata,
  ): Promise<QueryGetProtocolFeesResponse>;
  /** ListSolverData Queries a list of SolverData items. */
  GetSolverData(
    request: DeepPartial<QueryGetSolverDataRequest>,
    metadata?: grpc.Metadata,
  ): Promise<QueryGetSolverDataResponse>;
  /** ListSolverData defines the ListSolverData RPC. */
  ListSolverData(
    request: DeepPartial<QueryAllSolverDataRequest>,
    metadata?: grpc.Metadata,
  ): Promise<QueryAllSolverDataResponse>;
  /** ListSettlement Queries a list of Settlement items. */
  GetSettlement(
    request: DeepPartial<QueryGetSettlementRequest>,
    metadata?: grpc.Metadata,
  ): Promise<QueryGetSettlementResponse>;
  /** ListSettlement defines the ListSettlement RPC. */
  ListSettlement(
    request: DeepPartial<QueryAllSettlementRequest>,
    metadata?: grpc.Metadata,
  ): Promise<QueryAllSettlementResponse>;
}

export class QueryClientImpl implements Query {
  private readonly rpc: Rpc;

  constructor(rpc: Rpc) {
    this.rpc = rpc;
    this.GetRequestForFunds = this.GetRequestForFunds.bind(this);
    this.ListRequestForFunds = this.ListRequestForFunds.bind(this);
    this.GetPendingClaims = this.GetPendingClaims.bind(this);
    this.ListPendingClaims = this.ListPendingClaims.bind(this);
    this.GetPendingSettlements = this.GetPendingSettlements.bind(this);
    this.ListPendingSettlements = this.ListPendingSettlements.bind(this);
    this.GetProtocolFees = this.GetProtocolFees.bind(this);
    this.GetSolverData = this.GetSolverData.bind(this);
    this.ListSolverData = this.ListSolverData.bind(this);
    this.GetSettlement = this.GetSettlement.bind(this);
    this.ListSettlement = this.ListSettlement.bind(this);
  }

  GetRequestForFunds(
    request: DeepPartial<QueryGetRequestForFundsRequest>,
    metadata?: grpc.Metadata,
  ): Promise<QueryGetRequestForFundsResponse> {
    return this.rpc.unary(
      QueryGetRequestForFundsDesc,
      QueryGetRequestForFundsRequest.fromPartial(request),
      metadata,
    );
  }

  ListRequestForFunds(
    request: DeepPartial<QueryAllRequestForFundsRequest>,
    metadata?: grpc.Metadata,
  ): Promise<QueryAllRequestForFundsResponse> {
    return this.rpc.unary(
      QueryListRequestForFundsDesc,
      QueryAllRequestForFundsRequest.fromPartial(request),
      metadata,
    );
  }

  GetPendingClaims(
    request: DeepPartial<QueryGetPendingClaimsRequest>,
    metadata?: grpc.Metadata,
  ): Promise<QueryGetPendingClaimsResponse> {
    return this.rpc.unary(
      QueryGetPendingClaimsDesc,
      QueryGetPendingClaimsRequest.fromPartial(request),
      metadata,
    );
  }

  ListPendingClaims(
    request: DeepPartial<QueryAllPendingClaimsRequest>,
    metadata?: grpc.Metadata,
  ): Promise<QueryAllPendingClaimsResponse> {
    return this.rpc.unary(
      QueryListPendingClaimsDesc,
      QueryAllPendingClaimsRequest.fromPartial(request),
      metadata,
    );
  }

  GetPendingSettlements(
    request: DeepPartial<QueryGetPendingSettlementsRequest>,
    metadata?: grpc.Metadata,
  ): Promise<QueryGetPendingSettlementsResponse> {
    return this.rpc.unary(
      QueryGetPendingSettlementsDesc,
      QueryGetPendingSettlementsRequest.fromPartial(request),
      metadata,
    );
  }

  ListPendingSettlements(
    request: DeepPartial<QueryAllPendingSettlementsRequest>,
    metadata?: grpc.Metadata,
  ): Promise<QueryAllPendingSettlementsResponse> {
    return this.rpc.unary(
      QueryListPendingSettlementsDesc,
      QueryAllPendingSettlementsRequest.fromPartial(request),
      metadata,
    );
  }

  GetProtocolFees(
    request: DeepPartial<QueryGetProtocolFeesRequest>,
    metadata?: grpc.Metadata,
  ): Promise<QueryGetProtocolFeesResponse> {
    return this.rpc.unary(
      QueryGetProtocolFeesDesc,
      QueryGetProtocolFeesRequest.fromPartial(request),
      metadata,
    );
  }

  GetSolverData(
    request: DeepPartial<QueryGetSolverDataRequest>,
    metadata?: grpc.Metadata,
  ): Promise<QueryGetSolverDataResponse> {
    return this.rpc.unary(
      QueryGetSolverDataDesc,
      QueryGetSolverDataRequest.fromPartial(request),
      metadata,
    );
  }

  ListSolverData(
    request: DeepPartial<QueryAllSolverDataRequest>,
    metadata?: grpc.Metadata,
  ): Promise<QueryAllSolverDataResponse> {
    return this.rpc.unary(
      QueryListSolverDataDesc,
      QueryAllSolverDataRequest.fromPartial(request),
      metadata,
    );
  }

  GetSettlement(
    request: DeepPartial<QueryGetSettlementRequest>,
    metadata?: grpc.Metadata,
  ): Promise<QueryGetSettlementResponse> {
    return this.rpc.unary(
      QueryGetSettlementDesc,
      QueryGetSettlementRequest.fromPartial(request),
      metadata,
    );
  }

  ListSettlement(
    request: DeepPartial<QueryAllSettlementRequest>,
    metadata?: grpc.Metadata,
  ): Promise<QueryAllSettlementResponse> {
    return this.rpc.unary(
      QueryListSettlementDesc,
      QueryAllSettlementRequest.fromPartial(request),
      metadata,
    );
  }
}

export const QueryDesc = { serviceName: "xarchain.chainabstraction.v1.Query" };

export const QueryGetRequestForFundsDesc: UnaryMethodDefinitionish = {
  methodName: "GetRequestForFunds",
  service: QueryDesc,
  requestStream: false,
  responseStream: false,
  requestType: {
    serializeBinary() {
      return QueryGetRequestForFundsRequest.encode(this).finish();
    },
  } as any,
  responseType: {
    deserializeBinary(data: Uint8Array) {
      const value = QueryGetRequestForFundsResponse.decode(data);
      return {
        ...value,
        toObject() {
          return value;
        },
      };
    },
  } as any,
};

export const QueryListRequestForFundsDesc: UnaryMethodDefinitionish = {
  methodName: "ListRequestForFunds",
  service: QueryDesc,
  requestStream: false,
  responseStream: false,
  requestType: {
    serializeBinary() {
      return QueryAllRequestForFundsRequest.encode(this).finish();
    },
  } as any,
  responseType: {
    deserializeBinary(data: Uint8Array) {
      const value = QueryAllRequestForFundsResponse.decode(data);
      return {
        ...value,
        toObject() {
          return value;
        },
      };
    },
  } as any,
};

export const QueryGetPendingClaimsDesc: UnaryMethodDefinitionish = {
  methodName: "GetPendingClaims",
  service: QueryDesc,
  requestStream: false,
  responseStream: false,
  requestType: {
    serializeBinary() {
      return QueryGetPendingClaimsRequest.encode(this).finish();
    },
  } as any,
  responseType: {
    deserializeBinary(data: Uint8Array) {
      const value = QueryGetPendingClaimsResponse.decode(data);
      return {
        ...value,
        toObject() {
          return value;
        },
      };
    },
  } as any,
};

export const QueryListPendingClaimsDesc: UnaryMethodDefinitionish = {
  methodName: "ListPendingClaims",
  service: QueryDesc,
  requestStream: false,
  responseStream: false,
  requestType: {
    serializeBinary() {
      return QueryAllPendingClaimsRequest.encode(this).finish();
    },
  } as any,
  responseType: {
    deserializeBinary(data: Uint8Array) {
      const value = QueryAllPendingClaimsResponse.decode(data);
      return {
        ...value,
        toObject() {
          return value;
        },
      };
    },
  } as any,
};

export const QueryGetPendingSettlementsDesc: UnaryMethodDefinitionish = {
  methodName: "GetPendingSettlements",
  service: QueryDesc,
  requestStream: false,
  responseStream: false,
  requestType: {
    serializeBinary() {
      return QueryGetPendingSettlementsRequest.encode(this).finish();
    },
  } as any,
  responseType: {
    deserializeBinary(data: Uint8Array) {
      const value = QueryGetPendingSettlementsResponse.decode(data);
      return {
        ...value,
        toObject() {
          return value;
        },
      };
    },
  } as any,
};

export const QueryListPendingSettlementsDesc: UnaryMethodDefinitionish = {
  methodName: "ListPendingSettlements",
  service: QueryDesc,
  requestStream: false,
  responseStream: false,
  requestType: {
    serializeBinary() {
      return QueryAllPendingSettlementsRequest.encode(this).finish();
    },
  } as any,
  responseType: {
    deserializeBinary(data: Uint8Array) {
      const value = QueryAllPendingSettlementsResponse.decode(data);
      return {
        ...value,
        toObject() {
          return value;
        },
      };
    },
  } as any,
};

export const QueryGetProtocolFeesDesc: UnaryMethodDefinitionish = {
  methodName: "GetProtocolFees",
  service: QueryDesc,
  requestStream: false,
  responseStream: false,
  requestType: {
    serializeBinary() {
      return QueryGetProtocolFeesRequest.encode(this).finish();
    },
  } as any,
  responseType: {
    deserializeBinary(data: Uint8Array) {
      const value = QueryGetProtocolFeesResponse.decode(data);
      return {
        ...value,
        toObject() {
          return value;
        },
      };
    },
  } as any,
};

export const QueryGetSolverDataDesc: UnaryMethodDefinitionish = {
  methodName: "GetSolverData",
  service: QueryDesc,
  requestStream: false,
  responseStream: false,
  requestType: {
    serializeBinary() {
      return QueryGetSolverDataRequest.encode(this).finish();
    },
  } as any,
  responseType: {
    deserializeBinary(data: Uint8Array) {
      const value = QueryGetSolverDataResponse.decode(data);
      return {
        ...value,
        toObject() {
          return value;
        },
      };
    },
  } as any,
};

export const QueryListSolverDataDesc: UnaryMethodDefinitionish = {
  methodName: "ListSolverData",
  service: QueryDesc,
  requestStream: false,
  responseStream: false,
  requestType: {
    serializeBinary() {
      return QueryAllSolverDataRequest.encode(this).finish();
    },
  } as any,
  responseType: {
    deserializeBinary(data: Uint8Array) {
      const value = QueryAllSolverDataResponse.decode(data);
      return {
        ...value,
        toObject() {
          return value;
        },
      };
    },
  } as any,
};

export const QueryGetSettlementDesc: UnaryMethodDefinitionish = {
  methodName: "GetSettlement",
  service: QueryDesc,
  requestStream: false,
  responseStream: false,
  requestType: {
    serializeBinary() {
      return QueryGetSettlementRequest.encode(this).finish();
    },
  } as any,
  responseType: {
    deserializeBinary(data: Uint8Array) {
      const value = QueryGetSettlementResponse.decode(data);
      return {
        ...value,
        toObject() {
          return value;
        },
      };
    },
  } as any,
};

export const QueryListSettlementDesc: UnaryMethodDefinitionish = {
  methodName: "ListSettlement",
  service: QueryDesc,
  requestStream: false,
  responseStream: false,
  requestType: {
    serializeBinary() {
      return QueryAllSettlementRequest.encode(this).finish();
    },
  } as any,
  responseType: {
    deserializeBinary(data: Uint8Array) {
      const value = QueryAllSettlementResponse.decode(data);
      return {
        ...value,
        toObject() {
          return value;
        },
      };
    },
  } as any,
};

interface UnaryMethodDefinitionishR
  extends grpc.UnaryMethodDefinition<any, any> {
  requestStream: any;
  responseStream: any;
}

type UnaryMethodDefinitionish = UnaryMethodDefinitionishR;

interface Rpc {
  unary<T extends UnaryMethodDefinitionish>(
    methodDesc: T,
    request: any,
    metadata: grpc.Metadata | undefined,
  ): Promise<any>;
}

export class GrpcWebImpl {
  private host: string;
  private options: {
    transport?: grpc.TransportFactory;

    debug?: boolean;
    metadata?: grpc.Metadata;
    upStreamRetryCodes?: number[];
  };

  constructor(
    host: string,
    options: {
      transport?: grpc.TransportFactory;

      debug?: boolean;
      metadata?: grpc.Metadata;
      upStreamRetryCodes?: number[];
    },
  ) {
    this.host = host;
    this.options = options;
  }

  unary<T extends UnaryMethodDefinitionish>(
    methodDesc: T,
    _request: any,
    metadata: grpc.Metadata | undefined,
  ): Promise<any> {
    const request = { ..._request, ...methodDesc.requestType };
    const maybeCombinedMetadata =
      metadata && this.options.metadata
        ? new BrowserHeaders({
            ...this.options?.metadata.headersMap,
            ...metadata?.headersMap,
          })
        : (metadata ?? this.options.metadata);
    return new Promise((resolve, reject) => {
      grpc.unary(methodDesc, {
        request,
        host: this.host,
        metadata: maybeCombinedMetadata ?? {},
        ...(this.options.transport !== undefined
          ? { transport: this.options.transport }
          : {}),
        debug: this.options.debug ?? false,
        onEnd: function (response) {
          if (response.status === grpc.Code.OK) {
            resolve(response.message!.toObject());
          } else {
            const err = new GrpcWebError(
              response.statusMessage,
              response.status,
              response.trailers,
            );
            reject(err);
          }
        },
      });
    });
  }
}

type Builtin =
  | Date
  | Function
  | Uint8Array
  | string
  | number
  | boolean
  | undefined;

export type DeepPartial<T> = T extends Builtin
  ? T
  : T extends Long
    ? string | number | Long
    : T extends globalThis.Array<infer U>
      ? globalThis.Array<DeepPartial<U>>
      : T extends ReadonlyArray<infer U>
        ? ReadonlyArray<DeepPartial<U>>
        : T extends { $case: string; value: unknown }
          ? { $case: T["$case"]; value?: DeepPartial<T["value"]> }
          : T extends {}
            ? { [K in keyof T]?: DeepPartial<T[K]> }
            : Partial<T>;

export class GrpcWebError extends globalThis.Error {
  constructor(
    message: string,
    public code: grpc.Code,
    public metadata: grpc.Metadata,
  ) {
    super(message);
  }
}
