// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.5
//   protoc               v6.32.1
// source: grpc.proto

/* eslint-disable */
import { grpc } from "@improbable-eng/grpc-web";
import { BrowserHeaders } from "browser-headers";
import Long from "long";
import {
  QueryAllRequestForFundsRequest,
  QueryAllRequestForFundsResponse,
  QueryAllSettlementRequest,
  QueryAllSettlementResponse,
  QueryAllSolverDataRequest,
  QueryAllSolverDataResponse,
  QueryGetPriceOracleDataRequest,
  QueryGetPriceOracleDataResponse,
  QueryGetProtocolFeesRequest,
  QueryGetProtocolFeesResponse,
  QueryGetRequestForFundsRequest,
  QueryGetRequestForFundsResponse,
  QueryGetSettlementRequest,
  QueryGetSettlementResponse,
  QueryGetSolverDataRequest,
  QueryGetSolverDataResponse,
  QueryRequestForFundsByAddressRequest,
} from "./definition";

export const protobufPackage = "xarchain.chainabstraction";

export interface Query {
  RequestForFunds(
    request: DeepPartial<QueryGetRequestForFundsRequest>,
    metadata?: grpc.Metadata,
  ): Promise<QueryGetRequestForFundsResponse>;
  RequestForFundsAll(
    request: DeepPartial<QueryAllRequestForFundsRequest>,
    metadata?: grpc.Metadata,
  ): Promise<QueryAllRequestForFundsResponse>;
  RequestForFundsByAddress(
    request: DeepPartial<QueryRequestForFundsByAddressRequest>,
    metadata?: grpc.Metadata,
  ): Promise<QueryAllRequestForFundsResponse>;
  SolverData(
    request: DeepPartial<QueryGetSolverDataRequest>,
    metadata?: grpc.Metadata,
  ): Promise<QueryGetSolverDataResponse>;
  SolverDataAll(
    request: DeepPartial<QueryAllSolverDataRequest>,
    metadata?: grpc.Metadata,
  ): Promise<QueryAllSolverDataResponse>;
  Settlement(
    request: DeepPartial<QueryGetSettlementRequest>,
    metadata?: grpc.Metadata,
  ): Promise<QueryGetSettlementResponse>;
  SettlementAll(
    request: DeepPartial<QueryAllSettlementRequest>,
    metadata?: grpc.Metadata,
  ): Promise<QueryAllSettlementResponse>;
  ProtocolFees(
    request: DeepPartial<QueryGetProtocolFeesRequest>,
    metadata?: grpc.Metadata,
  ): Promise<QueryGetProtocolFeesResponse>;
  PriceOracleData(
    request: DeepPartial<QueryGetPriceOracleDataRequest>,
    metadata?: grpc.Metadata,
  ): Promise<QueryGetPriceOracleDataResponse>;
}

export class QueryClientImpl implements Query {
  private readonly rpc: Rpc;

  constructor(rpc: Rpc) {
    this.rpc = rpc;
    this.RequestForFunds = this.RequestForFunds.bind(this);
    this.RequestForFundsAll = this.RequestForFundsAll.bind(this);
    this.RequestForFundsByAddress = this.RequestForFundsByAddress.bind(this);
    this.SolverData = this.SolverData.bind(this);
    this.SolverDataAll = this.SolverDataAll.bind(this);
    this.Settlement = this.Settlement.bind(this);
    this.SettlementAll = this.SettlementAll.bind(this);
    this.ProtocolFees = this.ProtocolFees.bind(this);
    this.PriceOracleData = this.PriceOracleData.bind(this);
  }

  RequestForFunds(
    request: DeepPartial<QueryGetRequestForFundsRequest>,
    metadata?: grpc.Metadata,
  ): Promise<QueryGetRequestForFundsResponse> {
    return this.rpc.unary(
      QueryRequestForFundsDesc,
      QueryGetRequestForFundsRequest.fromPartial(request),
      metadata,
    );
  }

  RequestForFundsAll(
    request: DeepPartial<QueryAllRequestForFundsRequest>,
    metadata?: grpc.Metadata,
  ): Promise<QueryAllRequestForFundsResponse> {
    return this.rpc.unary(
      QueryRequestForFundsAllDesc,
      QueryAllRequestForFundsRequest.fromPartial(request),
      metadata,
    );
  }

  RequestForFundsByAddress(
    request: DeepPartial<QueryRequestForFundsByAddressRequest>,
    metadata?: grpc.Metadata,
  ): Promise<QueryAllRequestForFundsResponse> {
    return this.rpc.unary(
      QueryRequestForFundsByAddressDesc,
      QueryRequestForFundsByAddressRequest.fromPartial(request),
      metadata,
    );
  }

  SolverData(
    request: DeepPartial<QueryGetSolverDataRequest>,
    metadata?: grpc.Metadata,
  ): Promise<QueryGetSolverDataResponse> {
    return this.rpc.unary(
      QuerySolverDataDesc,
      QueryGetSolverDataRequest.fromPartial(request),
      metadata,
    );
  }

  SolverDataAll(
    request: DeepPartial<QueryAllSolverDataRequest>,
    metadata?: grpc.Metadata,
  ): Promise<QueryAllSolverDataResponse> {
    return this.rpc.unary(
      QuerySolverDataAllDesc,
      QueryAllSolverDataRequest.fromPartial(request),
      metadata,
    );
  }

  Settlement(
    request: DeepPartial<QueryGetSettlementRequest>,
    metadata?: grpc.Metadata,
  ): Promise<QueryGetSettlementResponse> {
    return this.rpc.unary(
      QuerySettlementDesc,
      QueryGetSettlementRequest.fromPartial(request),
      metadata,
    );
  }

  SettlementAll(
    request: DeepPartial<QueryAllSettlementRequest>,
    metadata?: grpc.Metadata,
  ): Promise<QueryAllSettlementResponse> {
    return this.rpc.unary(
      QuerySettlementAllDesc,
      QueryAllSettlementRequest.fromPartial(request),
      metadata,
    );
  }

  ProtocolFees(
    request: DeepPartial<QueryGetProtocolFeesRequest>,
    metadata?: grpc.Metadata,
  ): Promise<QueryGetProtocolFeesResponse> {
    return this.rpc.unary(
      QueryProtocolFeesDesc,
      QueryGetProtocolFeesRequest.fromPartial(request),
      metadata,
    );
  }

  PriceOracleData(
    request: DeepPartial<QueryGetPriceOracleDataRequest>,
    metadata?: grpc.Metadata,
  ): Promise<QueryGetPriceOracleDataResponse> {
    return this.rpc.unary(
      QueryPriceOracleDataDesc,
      QueryGetPriceOracleDataRequest.fromPartial(request),
      metadata,
    );
  }
}

export const QueryDesc = { serviceName: "xarchain.chainabstraction.Query" };

export const QueryRequestForFundsDesc: UnaryMethodDefinitionish = {
  methodName: "RequestForFunds",
  service: QueryDesc,
  requestStream: false,
  responseStream: false,
  requestType: {
    serializeBinary() {
      return QueryGetRequestForFundsRequest.encode(this).finish();
    },
  } as any,
  responseType: {
    deserializeBinary(data: Uint8Array) {
      const value = QueryGetRequestForFundsResponse.decode(data);
      return {
        ...value,
        toObject() {
          return value;
        },
      };
    },
  } as any,
};

export const QueryRequestForFundsAllDesc: UnaryMethodDefinitionish = {
  methodName: "RequestForFundsAll",
  service: QueryDesc,
  requestStream: false,
  responseStream: false,
  requestType: {
    serializeBinary() {
      return QueryAllRequestForFundsRequest.encode(this).finish();
    },
  } as any,
  responseType: {
    deserializeBinary(data: Uint8Array) {
      const value = QueryAllRequestForFundsResponse.decode(data);
      return {
        ...value,
        toObject() {
          return value;
        },
      };
    },
  } as any,
};

export const QueryRequestForFundsByAddressDesc: UnaryMethodDefinitionish = {
  methodName: "RequestForFundsByAddress",
  service: QueryDesc,
  requestStream: false,
  responseStream: false,
  requestType: {
    serializeBinary() {
      return QueryRequestForFundsByAddressRequest.encode(this).finish();
    },
  } as any,
  responseType: {
    deserializeBinary(data: Uint8Array) {
      const value = QueryAllRequestForFundsResponse.decode(data);
      return {
        ...value,
        toObject() {
          return value;
        },
      };
    },
  } as any,
};

export const QuerySolverDataDesc: UnaryMethodDefinitionish = {
  methodName: "SolverData",
  service: QueryDesc,
  requestStream: false,
  responseStream: false,
  requestType: {
    serializeBinary() {
      return QueryGetSolverDataRequest.encode(this).finish();
    },
  } as any,
  responseType: {
    deserializeBinary(data: Uint8Array) {
      const value = QueryGetSolverDataResponse.decode(data);
      return {
        ...value,
        toObject() {
          return value;
        },
      };
    },
  } as any,
};

export const QuerySolverDataAllDesc: UnaryMethodDefinitionish = {
  methodName: "SolverDataAll",
  service: QueryDesc,
  requestStream: false,
  responseStream: false,
  requestType: {
    serializeBinary() {
      return QueryAllSolverDataRequest.encode(this).finish();
    },
  } as any,
  responseType: {
    deserializeBinary(data: Uint8Array) {
      const value = QueryAllSolverDataResponse.decode(data);
      return {
        ...value,
        toObject() {
          return value;
        },
      };
    },
  } as any,
};

export const QuerySettlementDesc: UnaryMethodDefinitionish = {
  methodName: "Settlement",
  service: QueryDesc,
  requestStream: false,
  responseStream: false,
  requestType: {
    serializeBinary() {
      return QueryGetSettlementRequest.encode(this).finish();
    },
  } as any,
  responseType: {
    deserializeBinary(data: Uint8Array) {
      const value = QueryGetSettlementResponse.decode(data);
      return {
        ...value,
        toObject() {
          return value;
        },
      };
    },
  } as any,
};

export const QuerySettlementAllDesc: UnaryMethodDefinitionish = {
  methodName: "SettlementAll",
  service: QueryDesc,
  requestStream: false,
  responseStream: false,
  requestType: {
    serializeBinary() {
      return QueryAllSettlementRequest.encode(this).finish();
    },
  } as any,
  responseType: {
    deserializeBinary(data: Uint8Array) {
      const value = QueryAllSettlementResponse.decode(data);
      return {
        ...value,
        toObject() {
          return value;
        },
      };
    },
  } as any,
};

export const QueryProtocolFeesDesc: UnaryMethodDefinitionish = {
  methodName: "ProtocolFees",
  service: QueryDesc,
  requestStream: false,
  responseStream: false,
  requestType: {
    serializeBinary() {
      return QueryGetProtocolFeesRequest.encode(this).finish();
    },
  } as any,
  responseType: {
    deserializeBinary(data: Uint8Array) {
      const value = QueryGetProtocolFeesResponse.decode(data);
      return {
        ...value,
        toObject() {
          return value;
        },
      };
    },
  } as any,
};

export const QueryPriceOracleDataDesc: UnaryMethodDefinitionish = {
  methodName: "PriceOracleData",
  service: QueryDesc,
  requestStream: false,
  responseStream: false,
  requestType: {
    serializeBinary() {
      return QueryGetPriceOracleDataRequest.encode(this).finish();
    },
  } as any,
  responseType: {
    deserializeBinary(data: Uint8Array) {
      const value = QueryGetPriceOracleDataResponse.decode(data);
      return {
        ...value,
        toObject() {
          return value;
        },
      };
    },
  } as any,
};

interface UnaryMethodDefinitionishR
  extends grpc.UnaryMethodDefinition<any, any> {
  requestStream: any;
  responseStream: any;
}

type UnaryMethodDefinitionish = UnaryMethodDefinitionishR;

interface Rpc {
  unary<T extends UnaryMethodDefinitionish>(
    methodDesc: T,
    request: any,
    metadata: grpc.Metadata | undefined,
  ): Promise<any>;
}

export class GrpcWebImpl {
  private host: string;
  private options: {
    transport?: grpc.TransportFactory;

    debug?: boolean;
    metadata?: grpc.Metadata;
    upStreamRetryCodes?: number[];
  };

  constructor(
    host: string,
    options: {
      transport?: grpc.TransportFactory;

      debug?: boolean;
      metadata?: grpc.Metadata;
      upStreamRetryCodes?: number[];
    },
  ) {
    this.host = host;
    this.options = options;
  }

  unary<T extends UnaryMethodDefinitionish>(
    methodDesc: T,
    _request: any,
    metadata: grpc.Metadata | undefined,
  ): Promise<any> {
    const request = { ..._request, ...methodDesc.requestType };
    const maybeCombinedMetadata =
      metadata && this.options.metadata
        ? new BrowserHeaders({
            ...this.options?.metadata.headersMap,
            ...metadata?.headersMap,
          })
        : (metadata ?? this.options.metadata);
    return new Promise((resolve, reject) => {
      grpc.unary(methodDesc, {
        request,
        host: this.host,
        metadata: maybeCombinedMetadata ?? {},
        ...(this.options.transport !== undefined
          ? { transport: this.options.transport }
          : {}),
        debug: this.options.debug ?? false,
        onEnd: function (response) {
          if (response.status === grpc.Code.OK) {
            resolve(response.message!.toObject());
          } else {
            const err = new GrpcWebError(
              response.statusMessage,
              response.status,
              response.trailers,
            );
            reject(err);
          }
        },
      });
    });
  }
}

type Builtin =
  | Date
  | Function
  | Uint8Array
  | string
  | number
  | boolean
  | undefined;

export type DeepPartial<T> = T extends Builtin
  ? T
  : T extends Long
    ? string | number | Long
    : T extends globalThis.Array<infer U>
      ? globalThis.Array<DeepPartial<U>>
      : T extends ReadonlyArray<infer U>
        ? ReadonlyArray<DeepPartial<U>>
        : T extends { $case: string; value: unknown }
          ? { $case: T["$case"]; value?: DeepPartial<T["value"]> }
          : T extends {}
            ? { [K in keyof T]?: DeepPartial<T[K]> }
            : Partial<T>;

export class GrpcWebError extends globalThis.Error {
  constructor(
    message: string,
    public code: grpc.Code,
    public metadata: grpc.Metadata,
  ) {
    super(message);
  }
}
